version: '2.4'
services:
  mfem:
    build: ./mfem
    labels:
      io.balena.features.dbus: 1
    restart: always
    network_mode: host
  
  # https://github.com/balenablocks/hostname
  hostname:
    build: hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: mfem